// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI3xFQdNKR77qktHmQIKhN25MfGWDAeHs',
    appId: '1:572954299905:web:149e300e8d2bdcffcbba00',
    messagingSenderId: '572954299905',
    projectId: 'risefarmer-959f9',
    authDomain: 'risefarmer-959f9.firebaseapp.com',
    storageBucket: 'risefarmer-959f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYoJYy5IfDxF-D8oDyEtksJQwl1ApIvE',
    appId: '1:572954299905:android:7088c7bb3cf90758cbba00',
    messagingSenderId: '572954299905',
    projectId: 'risefarmer-959f9',
    storageBucket: 'risefarmer-959f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32zcgKb1WS4BiwLTHaOOQQmpAbvSx7mM',
    appId: '1:572954299905:ios:bf5e5b458fbc76aecbba00',
    messagingSenderId: '572954299905',
    projectId: 'risefarmer-959f9',
    storageBucket: 'risefarmer-959f9.appspot.com',
    iosBundleId: 'com.example.motionhack2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32zcgKb1WS4BiwLTHaOOQQmpAbvSx7mM',
    appId: '1:572954299905:ios:fdaffbb5efb15ad8cbba00',
    messagingSenderId: '572954299905',
    projectId: 'risefarmer-959f9',
    storageBucket: 'risefarmer-959f9.appspot.com',
    iosBundleId: 'com.example.motionhack2024.RunnerTests',
  );
}
